### ISSUE TITLE
Installation instructions from source are deprecated

### ISSUE THREAD

**Issue by pgr0ss** [git-duet/git-duet#103]
For installing from source, the README says:

```
GOVENDOREXPERIMENT=1 go get github.com/git-duet/git-duet/...
```

https://github.com/git-duet/git-duet/blob/23c54886c237fc896f17bffd8eb719e191300bae/README.md?plain=1#L55

However, that now seems deprecated:

```
% GOVENDOREXPERIMENT=1 go get github.com/git-duet/git-duet/...
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

I think now we want this, but I wasn't sure enough to open a PR:
```
go install github.com/git-duet/git-duet/...@latest
```

**Comment by jszwedko** [comment]
Indeed, I was happy to see them introduce `go install` for this usage to play better with Go modules. Thanks for reporting!
