### ISSUE TITLE
Homebrew tap for v0.9.0 is broken

### ISSUE THREAD

**Issue by textbook** [git-duet/git-duet#111]
The latest release to add M1 support (thanks!) looks to have the AMD and ARM binaries the wrong way around - if I install on M1 I get:

```bash
$ brew install git-duet
==> Downloading https://github.com/git-duet/git-duet/releases/download/0.9.0/darwin_amd64.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/36262960/82ceb596-ce7d-46fa-b83f-a2838
######################################################################## 100.0%
Error: git-duet: SHA256 mismatch
Expected: 7e72fb8425f49cf436ab3808273cb1013719ae39a66169adf0a1c2c8aa4a72fc
  Actual: 3e6b20dd909a0b47763f6659828ad5b3860dcf8995ff12d221d911b8ecdd51c3
    File: path/to/Homebrew/downloads/d475fba919056de3d47db14fb3cfa621a5574a2b35c2076dd1474ecd23647bf8--darwin_amd64.tar.gz
To retry an incomplete download, remove the file above.
```

and vice versa on an Intel machine. Looking at the [relevant code][1]:

```ruby
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/git-duet/git-duet/releases/download/0.9.0/darwin_arm64.tar.gz"
      sha256 "3e6b20dd909a0b47763f6659828ad5b3860dcf8995ff12d221d911b8ecdd51c3"
    elsif Hardware::CPU.arm?
      url "https://github.com/git-duet/git-duet/releases/download/0.9.0/darwin_amd64.tar.gz"
      sha256 "7e72fb8425f49cf436ab3808273cb1013719ae39a66169adf0a1c2c8aa4a72fc"
    end
  end
```

`_arm64` and `_amd64`  are under the wrong branches (although the hashes are correct).

Related: #97.

  [1]: https://github.com/git-duet/homebrew-tap/blob/8600cf5958f10f495fad7bf9c03d18310a3d1844/git-duet.rb#L6-L14

**Comment by jszwedko** [comment]
Doh, thanks for catching that @textbook . I didn't have a access to a mac to test. I opened https://github.com/git-duet/homebrew-tap/pull/11 to fix.

**Comment by textbook** [comment]
This is still broken - the reason I got a `SHA256 mismatch` rather than just getting the wrong binary is that the `sha256`s were the right way around, but the `url`s were the wrong way around. So although I'm now downloading the binary for the correct platform, I still get a hash mismatch. If I make the following change to Homebrew's repo copy, the install works:

```diff
   on_macos do
     if Hardware::CPU.intel?
       url "https://github.com/git-duet/git-duet/releases/download/0.9.0/darwin_amd64.tar.gz"
-      sha256 "7e72fb8425f49cf436ab3808273cb1013719ae39a66169adf0a1c2c8aa4a72fc"
+      sha256 "3e6b20dd909a0b47763f6659828ad5b3860dcf8995ff12d221d911b8ecdd51c3"
     elsif Hardware::CPU.arm?
       url "https://github.com/git-duet/git-duet/releases/download/0.9.0/darwin_arm64.tar.gz"
-      sha256 "3e6b20dd909a0b47763f6659828ad5b3860dcf8995ff12d221d911b8ecdd51c3"
+      sha256 "7e72fb8425f49cf436ab3808273cb1013719ae39a66169adf0a1c2c8aa4a72fc"
     end
   end
```

I opened a PR to apply this (which is what I probably should have done to start with rather than just trying to describe the change needed!)
