### ISSUE TITLE
Running git-duet with no authors results in segfault

### ISSUE THREAD

**Issue by mclarke47** [git-duet/git-duet#115]
```
$  git duet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1022ff9c8]

goroutine 1 [running]:
github.com/git-duet/git-duet.(*GitConfig).setAuthor(0x1400011ff28, 0x0, 0x0, 0x0)
	/home/runner/work/git-duet/git-duet/git_config.go:161 +0x198
github.com/git-duet/git-duet.(*GitConfig).SetAuthor(0x1400011ff28, 0x0, 0x0, 0x0)
	/home/runner/work/git-duet/git-duet/git_config.go:105 +0x30
main.main()
	/home/runner/work/git-duet/git-duet/git-duet/main.go:77 +0xa58
```

**Comment by jszwedko** [comment]
Hi @mclarke47 !

Thanks for the report! I'm having trouble reproducing though. Which version of `git-duet`? Do you have an authors file? If so, could you share that as well?

**Comment by mclarke47** [comment]
Hi, I'm using `0.9.0 ('0b2a4f31724b585aeafdba91123fd4cd0d298445')` and my authors file looks like this:

```
authors:
  no: Name One; name1
  ....
email:
  domain: foo.com
```

**Comment by jszwedko** [comment]
Thanks @mclarke47 ! Oddly, I'm still having trouble reproducing this. I used the authors file you have there as-is (minus the `...`). Does the `panic` happen if you use the same authors file?

```yaml
authors:
  no: Name One; name1
email:
  domain: foo.com
```

In this scenario, have you already configured a pair via `git duet <initials>`? Or does this happen before configuring the active pair?

**Comment by jszwedko** [comment]
Also, which platform are you running on? I'm testing on Linux.

**Comment by mclarke47** [comment]
I'm on Mac M1. This is weird, I can no longer reproduce 😕. Not sure what changed in the meantime..

**Comment by jszwedko** [comment]
Weird. I took a look through and couldn't see how that null pointer exception _could_ be hit, but if you manage to reproduce it again, I'd love to hear how :smile: . I'll close this out for now.
