### ISSUE TITLE
Only one instead of multiple committers being added when mobbing

### ISSUE THREAD

**Issue by lx4r** [git-duet/git-duet#121]
Hey everyone,
for me the mobbing support isn't working properly. I'm using fish shell.

My config:

```fish
❯ echo $GIT_DUET_ALLOW_MULTIPLE_COMMITTERS
1
❯ echo $GIT_DUET_CO_AUTHORED_BY
```

`.git-authors`:

```
authors:
  b: Bob
  a: Alice
  c: Carol
email:
  domain: example.com
```

Executed commands:

```fish
❯ git duet a b c
GIT_AUTHOR_NAME='Alice'
GIT_AUTHOR_EMAIL='alice@example.com'
GIT_COMMITTER_NAME='Bob'
GIT_COMMITTER_EMAIL='bob@example.com'
❯ git duet-commit -v
```

The commit message I get:

```
Signed-off-by: Bob <bob@example.com>
```

What can I do to fix this and get Carol as a second committer?

Thanks in advance for the help :)

**Comment by jszwedko** [comment]
Hi @lx4r !

I think the multiple committer support is not in the latest release, 0.9.0. Would you be able to try building from source to see if it resolves your issue? If it does, we can cut a 0.10.0 release.

**Comment by lx4r** [comment]
@jszwedko Thanks for the reply!

I wasn't able to build git-duet on the machine that the problem occurred on (`darwin_arm64`) but was able to build it on a `linux-amd64` machine. Everything worked as intended while using fish shell like on the other machine:

```fish
❯ GIT_DUET_ALLOW_MULTIPLE_COMMITTERS=1 $GOPATH/bin/git-duet a b c
GIT_AUTHOR_NAME='Alice'
GIT_AUTHOR_EMAIL='alice@example.com'
GIT_COMMITTER_#1_NAME='Bob'
GIT_COMMITTER_#1_EMAIL='bob@example.com'
GIT_COMMITTER_#2_NAME='Carol'
GIT_COMMITTER_#2_EMAIL='carol@example.com'
❯ GIT_DUET_ALLOW_MULTIPLE_COMMITTERS=1 $GOPATH/bin/git-duet-commit -v
```

I got this commit message:

```

Signed-off-by: Bob <bob@example.com>
Signed-off-by: Carol <carol@example.com>
```

**Comment by jszwedko** [comment]
Great, thanks for confirming @lx4r ! It seems like we just need a new release then. I'll do that shortly.

**Comment by lx4r** [comment]
@jszwedko Awesome, thanks!
