### ISSUE TITLE
A global duet is ignored if there is an existing local duet even in global mode

### ISSUE THREAD

**Issue by tomwhoiscontrary** [git-duet/git-duet#14]
This bats test fails when run against 0.2.0:

```
@test "honours source when printing config after switching to global" {
  git duet -q al on
  export GIT_DUET_GLOBAL=true
  git duet -q jd fb
  run git duet
  assert_line "GIT_AUTHOR_NAME='Jane Doe'"
  assert_line "GIT_AUTHOR_EMAIL='jane@hamsters.biz.local'"
  assert_line "GIT_COMMITTER_NAME='Frances Bar'"
  assert_line "GIT_COMMITTER_EMAIL='f.bar@hamster.info.local'"
}
```

It fails because the al/on duet stays in effect; local duets override global duets, even if the global flag is set. This seems wrong to me.

We also observed inconsistency between `git duet` and `git duet-commit`; the former would print the right names, but the latter would commit with the wrong names. I'm not sure how that happened. I haven't written a bats test for this because involves a lot more plumbing in test_helper.sh!

Probably related to #11, may be fixed in master, haven't checked because building Go is hard waaaaah :baby_symbol:.

**Comment by jszwedko** [comment]
@tomwhoiscontrary interestingly I was just thinking about this. The current behavior (use local if set even when `GIT_DUET_GLOBAL=true`) is actually consistent with the ruby version this is ported from, but I agree that it doesn't feel quite right.

On one hand, I can see a workflow where you normally want `git duet` to operate against the global config, but want to override it in some repositories, but on the other I want there to be a `-g` flag available on every command and for `GIT_DUET_GLOBAL` to imply it for **all** commands.

Either way, it's definitely a bug that `git duet` will print out the globally set authors, but then end up reading the local authors when committing. I'm just not sure what the best solution is. I'm currently leaning towards the latter for more internal consistency.

**Comment by jszwedko** [comment]
I think it is mostly the environment variable that confuses things, otherwise it behave analogously to `git config -g user.name bar`, `git config user.name foo`, and `git commit` so its really about what the expectation of what the environment variable does.

**Comment by tomwhoiscontrary** [comment]
Yeah, this is all a bit confusing, isn't it? If it helps, ignore the semantics of the original Ruby implementation of `GIT_DUET_GLOBAL`, because that was written by a total fool.

I think the confusion stems from a bug, or at least a design flaw, in Git itself. Presumably this:

```
git config user.name MrLocal
git config -g user.name MsGlobal
git commit -am "who commits this?"
```

Ends up committing as MrLocal. Can you imagine a situation in which a user would want this?

The whole idea of managing user identity at the repository level stinks, if you ask me. It's something that should always be global, or at least be global by default.

**Comment by jszwedko** [comment]
Haha, nonsense, it was a good addition.

I agree in principle with respect to authorship configuration, but the question is what to do now that people are conditioned to that behavior in `git`. To be fair, I think the repo local configuration as default many of the options so it probably makes sense to make it consistent even if a bit undesirable for username / email when using `git config`.
