### ISSUE TITLE
symlinking ~/.pairs to ~/.git-authors no longer works

### ISSUE THREAD

**Issue by matt-royal** [git-duet/git-duet#19]
The README lists this as a valid configuration. However, when using the "stable 0.2.0" version of git-duet from homebrew, git-duet was not able to find any of our authors. Changing the top-level key from `pairs` to `authors` resolved the problem. It seems that either this behavior should be fixed or the instructions should be removed from the README.

**Comment by jszwedko** [comment]
@matt-royal thanks for catching this! It looks like the bug manifested if `pairs:` was not the first line of the `~/.git-authors`. I updated the test to not have it as the first line and fixed the behavior in https://github.com/git-duet/git-duet/commit/a4d879967403f9998cc39e5e057d2d69345516db.

**Comment by jszwedko** [comment]
Released in 0.3.0, thanks again for the report.
