### ISSUE TITLE
bats won't correctly fail

### ISSUE THREAD

**Issue by wendorf** [git-duet/git-duet#22]
I'm not totally sure what started causing this. I'm running git 2.6, but I've tried it with 2.5.x and 2.4.x. I'm interested in submitting another PR, but I can't write a failing test. For example, if I write:

``` bash
@test "addition using bc" {
  result="$(echo 2+2 | bc)"
  [ "$result" -eq 6 ]
}
```

...the test still passes (2+2 should not equal 6).

The test passes when I run `bats test` in the git-duet directory. If I comment out [this line](https://github.com/git-duet/git-duet/blob/master/test/test_helper.bash#L50) then my test starts failing. This has happened on OS X 10.10 and OS X 10.11. I wish I had a more specific cause to report, but I can't figure out why tests are failing to fail. More specifically, I don't know why they were correctly failing during the last time that I submitted a PR, but cannot fail now. All I did was update git (as far as I know), but rolling back to older gits doesn't fix anything.

Any idea?

**Comment by jszwedko** [comment]
@wendorf hmm, I added that test, as is, to the top of `git-duet.bats` and it failed as expected. I am running Git 2.1.4 (Debian repositories are lagging a little) though, I can try upgrading to see if that affects things.

**Comment by jszwedko** [comment]
I see the same behavior (the test fails) with Git 2.5.3 -- is possible to provide a patch I could apply to replicate your exact changes? My bats version is 0.4.0.

**Comment by wendorf** [comment]
@jszwedko Thanks for looking into it. I admit it's a pretty weird situation, especially since bats were working for me when I put together my PR.

[this commit](https://github.com/wendorf/git-duet/tree/should_fail_but_does_not) adds a new test file. If you run `bats test/should-fail.bats` I get a success. I found that by removing a line from the teardown function in [this commit](https://github.com/wendorf/git-duet/tree/should_fail_and_does), then the test correctly fails. I'm not sure why that line would cause incorrect failures, I'm pretty flummoxed.

Relevant versions of things:

``` bash
→ bats --version
Bats 0.4.0

→ git --version
git version 2.6.0

→ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11
BuildVersion:   15A284

→ git rev-parse HEAD
26b1945c1bff8cee73f191b3ec10844fc41da006 # as of this writing, the latest master
```

**Comment by jszwedko** [comment]
I installed the same version of Git to no avail :frowning: 

```
➜  test git:(should_fail_but_does_not) bats should-fail.bats 
 ✗ this should fail
   (in test file should-fail.bats, line 7)
     `[ "$result" -eq 10 ]' failed
   [master (root-commit) 4d71292] test commit for reverting
    1 file changed, 0 insertions(+), 0 deletions(-)
    create mode 100644 foo
   fatal: No such section!

1 test, 1 failure
➜  test git:(should_fail_but_does_not) git --version
git version 2.6.0
➜  test git:(should_fail_but_does_not) bats --version
Bats 0.4.0
➜  test git:(should_fail_but_does_not) uname -a
Linux jesse-laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
➜  test git:(should_fail_but_does_not) cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I can try to run it on an OSX machine tomorrow to see if somehow it makes a difference.

**Comment by jszwedko** [comment]
Very perplexing.

**Comment by jszwedko** [comment]
Neglected to try to run this at work yesterday, I'll shoot for Monday.

**Comment by jszwedko** [comment]
No such luck, :(

```
➜  test git:(should_fail_but_does_not) bats should-fail.bats
 ✗ this should fail
   (in test file should-fail.bats, line 7)
     `[ "$result" -eq 10 ]' failed
   [master (root-commit) 46640f2] test commit for reverting
    1 file changed, 0 insertions(+), 0 deletions(-)
    create mode 100644 foo
   fatal: No such section!

1 test, 1 failure
➜  test git:(should_fail_but_does_not) sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F27
➜  test git:(should_fail_but_does_not) bats --version
Bats 0.4.0
➜  test git:(should_fail_but_does_not) git --version
git version 2.6.1
```

**Comment by jszwedko** [comment]
Going to close this, but let me know if you want any more help troubleshooting @wendorf !
