### ISSUE TITLE
Support setting `user.name` and `user.email`

### ISSUE THREAD

**Issue by jszwedko** [git-duet/git-duet#4]
A difference from the Ruby implementation is that it also set the `user.name` and `user.email`. I can see both perspectives so I think we should allow this to be a configurable feature.

**Comment by aramprice** [comment]
It appears that when `user.name` and `user.email` are unset `git revert` does not pickup any author information.

**Comment by jszwedko** [comment]
@aramprice aaah, yes, good point -- though even then only the user would ever get picked up (since `git` doesn't have configuration options for the `committer`) so that isn't ideal either. Maybe this is the case for `git duet-revert`?

**Comment by aramprice** [comment]
@jszwedko - seems like a good case for it. Or maybe a flag to (temporarily) set `user.email` and `user.name`? 

`duet-revert` seems like a better option though.

**Comment by jszwedko** [comment]
Implemented git-duet-revert as #18

**Comment by codeword** [comment]
I think git-duet-revert is a fine addition to the project but I still think that git duet needs to modify the user.name and user.email variables.  There are lots of git commands that will result in commits, like rebase -i or rebase (with conflicts) or merge, or, or, or.  If the git duet implementation was to use the user.email and user.name for the author and then the [duet "env"] namespace for the committer and any other attributes the duet system needs, then when the user performs git actions that result in core git commits to happen, they would at the very least use one of the pair's credentials rather than some random users or machine name credentials

**Comment by jszwedko** [comment]
@codeword those are fair arguments (recently `git duet-merge` was added, but there are still others that aren't supported). I haven't had a chance to get to this yet, but implementations welcome!

**Comment by thewoolleyman** [comment]
Sorry for being dense about how git-duet actually works under the covers, but can you explain in detail what is meant by this statement above:

"git duet needs to modify the user.name and user.email variables"

What exactly is meant by that?  

A. Setting the ENV vars? or... 
B. setting them in the local .git/config or global ~/.gitconfig via `git config`?

...and my questions are:
1. what does git-duet currently do in other cases, if not either of those things?
2. If we did B. above, wouldn't that result in those values hanging around in config files outside of git-duet usage, which is (I would assume) undesirable?

Just trying to understand the details of the discussion around implementation for #25

Thanks,
-- Chad

**Comment by jszwedko** [comment]
@thewoolleyman apologies, I thought I'd responded to this already!

The intent of this issue is to modify the `user.name` and `user.email` `git config` variables that `git commit` and friends pick up on. This would allow non-`git-duet` commands to at least include one of the authors.

Currently `git-duet` sets namespaced variables in `git config` (under `[duet "env"]`) and sets them as the `GIT_COMMITTER_X` and `GIT_AUTHOR_X` environment variables which commands like `git commit` read from (the former only when `--signoff` is present). I.e. `git duet-commit` sets those variables and calls `git commit --signoff`.

You are correct in that it would affect operations outside of `git-duet-X` which is why I was why I didn't initially implement it, but I'm starting to see the case for it given the discussion on #25 where `git` complains about the lack of author for some operations.

**Comment by hjhart** [comment]
👍 

We are actually very interested in having `user.name` and `user.email` being set by git duet, as our engineer workstations are only used by engineers who are using git for pairing, and for applications like GitX and RubyMine, setting up a shim for both of them to use is more of a hassle than just setting `user.name` and `user.email`.

I'm happy to take a stab at this, but having someone point me in the right direction would be helpful. 

Seems like the convention would be to  set a environment variable, say, `GIT_DUET_SETS_USER_NAME_AND_USER_EMAIL` and have git-duet respond to that trigger.

**Comment by jszwedko** [comment]
Hi @hjhart,

Apologies for the delay. You are on the right track, having an environment variable that controls this behavior would be preferable. I'd be more than happy to review a PR to add this (I haven't had a chance to dig into it myself).

Thank you!

**Comment by WesleyJeanette** [comment]
We aren't able to rebase because `user.name` and `user.email` aren't set:

```
±  |master ↑1 ↓1 ✓| → git pull --rebase origin master
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
From github.com:some-repo/foo
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'user@machine.(none)')
You need to set your committer info first
±  |detached:origin/HEAD ✓| → git version
git version 2.5.4 (Apple Git-61)
```
