### ISSUE TITLE
0.5.0 darwin-amd64 artifcat does not include correct `git-duet` binary

### ISSUE THREAD

**Issue by friegger** [git-duet/git-duet#40]
Apparently the contained binaries are not correct. e.g. `git-duet --version` does not work. Can you have a look? https://github.com/git-duet/git-duet/releases/download/0.5.0/darwin_amd64.tar.gz

**Comment by jszwedko** [comment]
Doh, yep, I published an older revision to that release. Should be fixed now, thank you for alerting me!
