### ISSUE TITLE
Proposal: new flag `--respect-author` would solve some pain around rebases

### ISSUE THREAD

**Issue by cjcjameson** [git-duet/git-duet#52]
My teams have long used git-duet, and also been using a rebase-only git flow (no merge commits). See #24 and #25 for more background on the rebase pains.

I propose a new flag, `--respect-author`, for which the only different behavior is that `--amend` commands (including rebase) don't touch the author field. They might still add signoffs, and would certainly update the committer string based on who's currently the committer in the duet.

I think this would:
- save a lot of gymnastics around rebases
- keep the authorship intact
- emphasize the original meaning of "committer" in the git spec

@professor @thewoolleyman @glestaris for visibility

**Comment by jszwedko** [comment]
@cjcjameson can you clarify which `git-duet` commands would use this flag? I'm not sure I completely follow.

Thanks for opening this discussion!

**Comment by cjcjameson** [comment]
#53 did reasonably well to follow on to this issue; I'm content to close. We've been using https://github.com/kejadlen/git-together some recently and it's not perfect but good to experience both.
