### ISSUE TITLE
git duet-merge amends the last commit even when it is not a merge commit

### ISSUE THREAD

**Issue by kindrowboat** [git-duet/git-duet#55]
## Issue
When performing a no-op merge (i.e. all commits in the other branch are also in the branch that you're merging into) git duet still amends the last commit (which is not a merge commit.)  This causes a rewrite of history that may cause the branch to diverge from origin.

## Expected behavior
when performing a no-op merge, git duet-merge should not amend the latest commit.

## Steps to reproduce:
```
git init duet-merge-bug
cd duet-merge-bug
touch foo
git add .
git duet-commit -m "Made foo"
git checkout -b other-branch
git duet-merge master
git log master
git log other-branch
```

Notice that the "Made foo" commit each have different SHAs.

Doing the same thing but using `git merge` instead of `git duet-merge` yields the two commits having the same SHA.

**Comment by kindrowboat** [comment]
Should have mentioned that I'm using version 0.5.2.

**Comment by jszwedko** [comment]
Good catch, thanks @motevets ; thanks for the detailed steps to reproduce.

I think we can handle this by checking if `HEAD` is a merge commit after merging and only `amend`ing if so.

**Comment by jszwedko** [comment]
Let me now what you think of #58 @motevets
