### ISSUE TITLE
user: Current not implemented on darwin/amd64

### ISSUE THREAD

**Issue by philals** [git-duet/git-duet#66]
Hi

I installed via brew on OSX 10.13.3.

Using `git duet am pa` results in:

```
GIT_AUTHOR_NAME='Ax Mx'
GIT_AUTHOR_EMAIL='ax@x.com'
GIT_COMMITTER_NAME='Px Ax'
GIT_COMMITTER_EMAIL='px@x.com'
user: Current not implemented on darwin/amd64
exit status 1
```

From here it does not commit as expected with two names.

Doing some reading it looks like something to do with using the cross compiling:

https://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64

Happy to test out commands etc

**Comment by jszwedko** [comment]
Hi @philals!

I gave this a shot with the latest, 0.6.0, via homebrew on OSX (10.13.4), but was unfortunately wasn't able to reproduce.

Could you provide:

* the output of `git-duet -v`
* `env | grep -e HOME -e USER` in the same shell where it fails

Looking at https://github.com/golang/go/commit/795e712b72802ad49b7c077964046f79c4f6586e it seems like it should work without cgo (including cross-compiling) as of Go 1.7 (this version is compiled with 1.7.3).

Thank you!

**Comment by philals** [comment]
Thanks for the help @jszwedko 

Your comment made me review all my env vars. 

I had `USER` being set to an empty string for some reason. After removing the setting of that var from my bash_profile I am not longer getting that error.

Much appreciated. Thanks for making this product.

**Comment by jszwedko** [comment]
:+1: thanks for verifying @philals ! That error message is a bit misleading.
