### ISSUE TITLE
VSCode extension ✅

### ISSUE THREAD

**Issue by philals** [git-duet/git-duet#67]
Hi

I created a VSCode extension which sits on top of git duet: https://marketplace.visualstudio.com/items?itemName=PhilAlsford.git-duet-vscode

It was mainly for my use case. I wanted something that would remind me who I had set with `git duet`/`git solo`.

Looking for feedback/bugs/features etc. 

A few things to note: 
- It adds `git duet` and `git solo` as a VSCode command, and also `git as` which will conditionally do a `duet` or `solo` depending on how many initials you type.
- It uses `git duet` and therefor you need `GIT_DUET_SET_GIT_USER_CONFIG ` set as per the readme on git duet

Feel free to take it for a spin, PR or issues on it.

**Comment by jszwedko** [comment]
Very cool, thanks for creating this extension @philals ! If you want to, we could add a reference to the README somewhere around the [Rubymine integration](https://github.com/git-duet/git-duet#rubymine-integration).

I'll let others chime in with feedback since I don't experience with VSCode.

**Comment by philals** [comment]
Thanks for that.

Have done: https://github.com/git-duet/git-duet/pull/69
