### ISSUE TITLE
git solo + git duet = git as

### ISSUE THREAD

**Issue by philals** [git-duet/git-duet#70]
Hi

Just think, why not combine the two command as one, maybe `git as`. Under the hood, `git as` will just do an if statement. If there is on set of initials then `git solo` else `git duet`.

Ps This is what I did for the VSCode extension: https://marketplace.visualstudio.com/items?itemName=PhilAlsford.git-duet-vscode

**Comment by jszwedko** [comment]
👍 I think this is a good idea (and would welcome a PR 😄 ).

**Comment by rafecolton** [comment]
@jszwedko this seems like a good way to get my feet wet with the code again, assigning it to myself
