### ISSUE TITLE
Improve error message on parse error

### ISSUE THREAD

**Issue by bruce-ricard** [git-duet/git-duet#71]
If you have a syntax error in your `.git-authors` file, when you run `git solo` or `git duet` you'll get an error message of the type:

```
yaml: line 9: could not find expected ':'
```
You don't even know which file the message is referring to.

To reproduce, replace a colon by a semicolon in your git-authors file, and try to run `git solo xx`.

**Comment by jszwedko** [comment]
@bruce-ricard thanks for pointing this out! What do you think of #72 ?
