### ISSUE TITLE
Rotation even with Co-authored-by

### ISSUE THREAD

**Issue by Kiemes** [git-duet/git-duet#75]
We would like to keep the rotation even when using `Co-authored-by` without the need to run `git duet` again.
I understand that from a GitHub contributions point of view, there is no need for it, but is there any reason not to rotate?
The profile pictures per commit, which let you quickly see who did the commit, would then rotate. That seems fair.
Wdyt @jszwedko? @ansd maybe we could pair on that during a TGIF ;) 
Best regards, Tom

**Comment by ansd** [comment]
@Kiemes sounds good. Yes, let's do this together in our flex hours :)

@jszwedko probably rotating authors should run in a `post-commit` hook? Do you think this makes sense or would it be kind of overkill to introduce another hook for this feature? (It would be opt-in anyways by setting `GIT_DUET_ROTATE_AUTHOR`. If users don't like the `post-commit` hook, they don't need to set this environment variable?)

**Comment by jszwedko** [comment]
Thanks for the suggestion @Kiemes ! I missed this in the initial implementation of `GIT_DUET_CO_AUTHORED_BY`, but agree that it should respect `GIT_DUET_ROTATE_AUTHOR`.
