### ISSUE TITLE
Consider using bats-core

### ISSUE THREAD

**Issue by Kiemes** [git-duet/git-duet#78]
During the two PRs I stumbled upon [bats-core](https://github.com/bats-core/bats-core) which seems to be the more sophisticated continuation of the stale [bats](https://github.com/sstephenson/bats).

Wouldn't it be nice to move over?

**Comment by jszwedko** [comment]
@Kiemes ah, yes; I was aware `bats` was not actively maintained, but didn't realize another project picked up the mantle. I'd be happy to see us switch to `bats-core`.
